# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm install request
    - run: npm init -y

    - name: run helloweb.js
      id: hello
      run: node helloweb.js
      #continue-on-error: true

    - name: Check failure
      if: ${{ failure() }}
      run: node lineAPI.js

    - name: reRun helloweb.js
      run: node helloweb.js

    - name: Check on failures
      run: echo Check success!!
    